import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import {UserProvider} from "@auth0/nextjs-auth0/client";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Domain Tools",
    description: "Generated by fenda",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <UserProvider>
            <AntdRegistry>
                {children}
            </AntdRegistry>
        </UserProvider>
        </body>
        </html>
    );
}
